### ISSUE TITLE
Features for first major release

### ISSUE THREAD

**Issue by alexrutar** [autobib/autobib#5]
A collection of features that would be great to implement for the first major release.
- [x] #24 
- [x] #44 
- [x] Support `autobib edit` to update existing records (see also #39)
- [x] Citation parsing and autogeneration from `.tex` files (or other text sources)
- [ ] Multi-threading / async support #15
- [ ] Slugification, and friends:
  - [ ] #172 
  - [ ] #266 
- [x] #19 
- [ ] #231 
- [ ] #158 
- [ ] Support an initial collection of record resources:
  - [x] `local`: #39 
  - [x] `mr`: #13 
  - [x] `zbl`: zbMath external identifiers
  - [x] `jfm`: a zbMath identifier used for very old resources
  - [x] `doi`: DOI references (can use [crossref](https://www.crossref.org/documentation/retrieve-metadata/rest-api/) or [openaccessbutton](https://openaccessbutton.org/) which might also support PDF retrieval)
  - [x] `isbn`: #14 
  - [x] `ol`: #14 
- [ ] CLI features
  - [x] Sane [xdg defaults](https://whitequark.github.io/rust-xdg/xdg/)
  - [x] Improve CLI ergonomics:
    - [x] interactive prompting
    - [x] indicate progress to user with [indicatif](https://docs.rs/indicatif/latest/indicatif/); should just indicate how many 'remote' records are left
  - [x] Alias support
  - [ ] #29
  - [x] #43
    - [ ] Use local configuration file (e.g. `.autobib.toml`) #241 
    - [ ] Supply list of tex files to search for citations? e.g. for #29 (support globs with https://docs.rs/glob/latest/glob/)
  - [x] Convenient fuzzy searching
- [ ] Make a webpage
- [ ] Development stuff
  - [ ] Documentation
  - [ ] Tests
  - [x] Packaging / release automation
  - [ ] Go through [cargo manifest](https://doc.rust-lang.org/cargo/reference/manifest.html) and check if anything should be included
  - [x] Automated build, testing, clippy
